# Based off of https://github.com/cypress-io/cypress-example-todomvc/blob/master/.travis.yml
language: node_js

node_js:
  # Support 8.11 and up, as that is what we use
  - 8.11

# Cache NPM folder and Cypress binary
cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - npm install

script:
  - npm run lint
  - npm test

after_success:
  - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
